language: ruby

rvm:
  - jruby
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

bundler_args: --without development

sudo: false

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2

notifications:
  emails: true
